const express = require("express");
const router = express.Router();
const userController = require("../controllers/userController");
router.post("/", userController.createUser);
router.get("/:userName", userController.getUser);
router.post('/:userId/shopping-list', userController.addShoppingListItem);
router.get('/:userId/shopping-list', userController.getShoppingList);
router.delete('/:userId/shopping-list/:itemId',userController.deleteShoppingListItem );
router.post('/:userId/purchased-items', userController.addPurchasedItem);
router.put('/users/:userId/kitchen-items/:productName', userController.updateKitchenItemQuantity);
module.exports = router;
